language: node_js

node_js: 12

cache: npm

jobs:
  include:
    - stage: init
      script: npm ci
    - stage: test
      script: 
        - npm run lint
        - npm test
    - stage: build
      script: npm run build
    - stage: integration
      script: npm run test:integration
