language: node_js

node_js: 12

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

jobs:
  include:
    - stage: init
      script: npm ci
    - stage: test
      script: 
        - npm run lint
        - npm test
    - stage: integration
      script: npm run build
