name: 'npm-setup'
description: 'Groups all the npm setup steps'
runs:
  using: "composite"
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./node_modules
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Cache Cypress binary
      uses: actions/cache@v2
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ hashFiles('package-lock.json') }}
